export const ActionTypes = {
  CHECK_AUTH: "CHECK_AUTH",
  GET_PROPERTIES: "GET_PROPERTIES",
  ADD_REQUEST: "ADD_REQUEST",
  GET_REQUESTS: "GET_REQUESTS",
  GET_REQUESTS_BY_ID: "GET_REQUESTS_BY_ID",
};
